config/routes.rb
Rails.application.routes.draw do


  get '/members/user/new' => 'users#new'
  resources :users


  get 'se2sions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get  'about'=>  'static_pages#about'

  get 'contact' =>'static_pages#contact'


  get 'signup'  => 'members#new'
  get    'login'   => 'se2sions#new'
  post   'login'   => 'se2sions#create'
  delete 'logout'  => 'se2sions#destroy'
  get  'members_path' => 'members#index'
  get  'members/members_path' => 'members#index'
  get 'add_admin'  => 'members#add_admin'
  resources :members

  get 'searchbook' => 'members#find_book'

  resources :books

  resources :histories, only: [:create, :index]

  post 'register' => 'books#register' 

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def user_params
    params.require(:user).permit(:ISBN, :title, :author, :description, :status)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user= User.new(user_params)
    @user.status = "available"
    if @user.save
      flash[:success] = "Successfully send the suggestion. Please wait for processing. Thank you!"
      redirect_to '/'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully edit the suggested book"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Suggest denied"
    redirect_to users_url
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>

  <%= link_to user.ISBN, user %>

  <%= link_to user.title, user %>

  <%= link_to 'Edit', edit_user_path(user) %>

  <%= link_to 'Deny', user, method: :delete, data: { confirm: "You sure?" } %>

  <%= link_to 'Approve', books_path(:ISBN => user.ISBN,
                                                :title => user.title,
                                                :description => user.description,
                                                :author => user.author,
                                              :status => user.status
                                          ), method: :post%>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit suggest") %>
<h1>Edit Suggestion</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

        <%= f.label :ISBN %>
        <%= f.text_field :ISBN, class: 'form-control' %>

        <%= f.label :Title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :Author %>
        <%= f.text_field :author, class: 'form-control' %>

        <%= f.label :Description %>
        <%= f.text_field :description, class: 'form-control' %>

        <%= f.label :Status %>
        <%= f.text_field :status, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'suggests') %>
<h2>Suggested Books</h2>
<%= will_paginate %>

<% if @users != nil %>
<ul class="users">
  <% @users.each do |user| %>
      <%=render user%>
  <% end %>
</ul>
<% end %>


<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'User') %>
<h1>Suggest a book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= f.label :ISBN %>
        <%= f.text_field :ISBN %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <%= f.label :author %>
        <%= f.text_field :author %>
        <%= f.submit "Suggest a book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>

        <%= @user.title %>
      </h1>
    </section>
  </aside>
</div>