config/routes.rb
Rails.application.routes.draw do


  get '/members/user/new' => 'users#new'
  resources :users


  get 'se2sions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get  'about'=>  'static_pages#about'

  get 'contact' =>'static_pages#contact'


  get 'signup'  => 'members#new'
  get    'login'   => 'se2sions#new'
  post   'login'   => 'se2sions#create'
  delete 'logout'  => 'se2sions#destroy'
  get  'members_path' => 'members#index'
  get  'members/members_path' => 'members#index'
  get 'add_admin'  => 'members#add_admin'
  resources :members

  get 'searchbook' => 'members#find_book'

  resources :books

  resources :histories, only: [:create, :index]

  post 'register' => 'books#register' 

end

app/controllers/se2sions_controller.rb
class Se2sionsController < ApplicationController
  def new
  end
  def create
    member = Member.find_by(email: params[:se2sion][:email].downcase)
    if member && (member[:password]==(params[:se2sion][:password]))
      log_in member
      redirect_to member
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/se2sions_helper.rb
module Se2sionsHelper
  def log_in(member)
    session[:member_id] = member.id
  end
  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end
  def logged_in?
    !current_member.nil?
  end
  def log_out
    session.delete(:member_id)
    @current_member = nil
  end
  def current_member?(member)
    member == current_member 
  end

  def current_suggest
    @current_suggest ||= Suggest.find_by(id: session[:user_id])
  end

end

app/views/se2sions/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:se2sion, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New member? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>