config/routes.rb
Rails.application.routes.draw do


  get '/members/user/new' => 'users#new'
  resources :users


  get 'se2sions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get  'about'=>  'static_pages#about'

  get 'contact' =>'static_pages#contact'


  get 'signup'  => 'members#new'
  get    'login'   => 'se2sions#new'
  post   'login'   => 'se2sions#create'
  delete 'logout'  => 'se2sions#destroy'
  get  'members_path' => 'members#index'
  get  'members/members_path' => 'members#index'
  get 'add_admin'  => 'members#add_admin'
  resources :members

  get 'searchbook' => 'members#find_book'

  resources :books

  resources :histories, only: [:create, :index]

  post 'register' => 'books#register' 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The LibSys is developed</a>
    by <a href="https://github.com/Hongyi23/LibSys">Huanyu Xia, Hongyi Ma, Ying Huang.</a>
  </small>
  <nav> <ul>
    <li><%= link_to "About",   about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul> </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "LybSys", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if logged_in? %> 
        <li><%= link_to "Home", current_member %></li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
        <% end %>
        <li><%= link_to "Help", help_path%></li>
        <% if logged_in? && current_member.admin? %>


          <li><%= link_to "Members", 'members_path' %></li>
        <%end%>


        <% if logged_in? %>



           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_member %></li>
              <li><%= link_to "Edit profile", edit_member_path(current_member) %></li>

              <%if ! current_member.admin?%>

                  <li><%= link_to "Suggest a book", '/members/user/new' %></li>
              <%end%>


              <% if current_member.admin?%>
                  <li><%= link_to "Add member&admin ", add_admin_path%></li>
                  <li><%= link_to "View suggestion", '/users' %></li>

              <% end %>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>