config/routes.rb
Rails.application.routes.draw do


  get '/members/user/new' => 'users#new'
  resources :users


  get 'se2sions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get  'about'=>  'static_pages#about'

  get 'contact' =>'static_pages#contact'


  get 'signup'  => 'members#new'
  get    'login'   => 'se2sions#new'
  post   'login'   => 'se2sions#create'
  delete 'logout'  => 'se2sions#destroy'
  get  'members_path' => 'members#index'
  get  'members/members_path' => 'members#index'
  get 'add_admin'  => 'members#add_admin'
  resources :members

  get 'searchbook' => 'members#find_book'

  resources :books

  resources :histories, only: [:create, :index]

  post 'register' => 'books#register' 

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :histories, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :logged_in_member, only: [:index, :edit, :update, :destroy]
  before_action :correct_member, only: [ :edit, :update]
  before_action :admin_member, only: [:index, :destroy]

  def new
    @member = Member.new
  end

  def show
    @member = Member.find(params[:id])
    @histories = @member.histories.paginate(page: params[:page])
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      if current_member != nil && current_member.admin?
        flash[:success] = "Member #{@member.name} added"
        redirect_to members_path
      else
        flash[:success] = "Welcome to Library System"
        log_in @member
        redirect_to @member
      end
    else
      render 'new'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(member_params)
      flash[:success] = "Profile updated"
      redirect_to @member
    else
      render 'edit'
    end
  end


  def index
    @members = Member.paginate(page: params[:page])
  end


  def destroy
    member_history = Member.find(params[:id]).histories
    check = 0
    ret = 0

    if member_history.any?
      member_history.each do |history|
        (history.action == "checkout") ? check += 1: ret += 1
      end
      if check > ret
        flash[:danger] = "Cannot delete: this member has books need to be returned"
        redirect_to members_url
      else
        Member.find(params[:id]).destroy
        flash[:success] = "Member deleted"
        redirect_to members_url
      end
    else
      Member.find(params[:id]).destroy
      flash[:success] = "Member deleted"
      redirect_to members_url
    end
  end

  def admin_member
    redirect_to(root_url) unless current_member.admin?
  end
  
  def find_book
    if params[:search]
      if params[:classify] == "ISBN" || params[:classify] == "title" || params[:classify] == "author" || params[:classify] == "description" || params[:classify] == "status"
        @books = Book.where("#{params[:classify]} LIKE ?", "%#{params[:search]}%")
      else
        flash[:danger] = "Can not search by #{params[:classify]}"
        redirect_to searchbook_path
      end
    end
  end

  def add_admin
    @member = Member.new
  end

private

  def member_params
    params.require(:member).permit(:name, :email, :password,:admin) #保存相应的value
  end 

  def logged_in_member
    unless logged_in?
      flash[:danger] = "Please log in."
        redirect_to login_url
    end
  end


  def correct_member
    @member = Member.find(params[:id])
    redirect_to(root_url) unless @member == current_member
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.erb
<li>
  <%= link_to member.name, member %>

  <% if member.pre?  %>
  <%="(Pre admin)"%>
  <% end %>

  <% if member.admin? && !member.pre? %>
      <%=  "(admin)" %>
  <% elsif !member.admin? %>
      <%=  "(member)" %>
  <% end %>




  <% if current_member.admin? && !current_member?(member) && !member.pre? %>
      |
      <%= link_to "delete", member, method: :delete,
                  data: {confirm: "You sure?"} %>

  <% end %>

</li>

app/views/members/add_admin.html.erb
<% provide(:title, 'Add admin') %>
<h1>Add members or admins</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>

        <div class="field">
          <%= f.label "Check to set as a admin:" %> <br />
          <%= f.check_box :admin%> <br />
        </div>
        <%= f.submit "Create", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/members/edit.html.erb
<% provide(:title, "Edit member") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/members/find_book.html.erb
<% provide(:title, 'Find book') %>
<h1>Search book</h1>

<%= form_tag searchbook_path, :method => 'get' do %>
    <p>
      <strong>Key word: </strong><%= text_field_tag :search, params[:search] %>
      <strong>Find by: </strong><%= text_field_tag :classify, params[:classify] %>
      (Please input "ISBN", "author", "title", "description", "status")
    </p>
    <p>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<table>
  <thead>
  <tr>
    <th>ISBN</th>
    <th>Title</th>
    <th>Author</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>

  <ul class="books">

    <% if @books != nil %>
    <% @books.each do |book| %>
        <tr>
          <td><%= book.ISBN %></td>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.status %></td>
          <td><%= link_to 'Detail', book %></td>
        </tr>
    <% end %>
    <% end %>

  </ul>

  </tbody>
</table>

<%= link_to "Back", member_path(current_member) %>

app/views/members/index.html.erb
<% provide(:title, 'All members') %>

<h1>All members</h1>

<%= will_paginate %>

<ul class="members">

  <% @members.each do |member| %>
      <%= render member %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/members/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
            
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>



      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<h1>Member Page</h1>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <p>
          <strong>Name:</strong>
          <%=@member.name%>
        </p>

        <p>
          <strong>Email:</strong>
          <%=@member.email%>
        </p>

        <p>
          <%= link_to "All books", books_path %>
        </p>

      <p>
        <%= link_to "Search books", searchbook_path %>
      </p>
      <% if current_member.admin? %>
        <p>
           <%= link_to "Add a book", new_book_path %>
        </p>
      <% end %>

      <p>
        <%= link_to "Library Record", histories_path(:member_id => @member.id), method: :get %>
      </p>
    </section>
  </aside>


  <div class="col-md-8">

    <h3>Books need to be returned</h3>
    <ol class="histories">

    <% allbook = [] %>

    <!--get all the book related with this member-->
    <% current_member.histories.each do |myhis| %>
      <% allbook << myhis.book_id %>
    <% end %>

    <!--delete duplicate-->
    <% allbook = allbook.uniq %>
    <% flag_to_show_no_record = TRUE %>

    <!--for each book, find the last record, check if it need to be returned-->
    <% allbook.each do |book| %>
        <% record = nil %>
        <% current_member.histories.each do |myhis| %>
          <% if book == myhis.book_id%>
            <% record = myhis %>    <!--find the last record-->
          <% end %>
        <% end %>
        <!--check the action of the record-->
        <% if record.action == "checkout" %>   <!--need to be returned-->
          <span class="book">
            <%= link_to record.book.title, record.book %>
          </span>
          <% flag_to_show_no_record = FALSE %>

        <% end %>
    <% end %>

    <!--see if all the books are returned-->
    <% if flag_to_show_no_record %>
        <p>
          No record.
        </p>
    <% end %>
    </ol>

  </div>
</div>